Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,11 +1,57 @@
-name: Deploy
+name: Deploy to test servers
 
-# Controls when the action will run. Workflow runs on push and pull request events.
+
 on:
   workflow_dispatch:
+    inputs:
+      HELIOS_TRIGGERED_BY:
+        description: "Username that triggered deployment"
+        required: true
+        type: string
+      HELIOS_BRANCH_NAME:
+        description: "Which branch to deploy"
+        required: true
+        type: string
+      HELIOS_BRANCH_HEAD_SHA:
+        description: "SHA of the branch to deploy"
+        required: true
+        type: string
+      HELIOS_ENVIRONMENT_NAME:
+        description: "Which environment to deploy (e.g. artemis-test7.artemis.cit.tum.de, etc.)."
+        required: true
+        type: string
+      HELIOS_RAW_URL:
+        description: "URL to the raw content of the repository in the format https://raw.githubusercontent.com/:owner/:repo/:sha"
+        required: true
+        type: string
+      HELIOS_BUILD:
+        description: "Whether to also build or just deploy the existing Docker image"
+        required: true
+        type: boolean
+      HELIOS_PR_NUMBER:
+        description: "PR number that triggered deployment"
+        required: false
+        type: string
+      HELIOS_BUILD_TAG:
+        description: "Docker tag to use if we are building or pulling an existing image"
+        required: false
+        type: string
+
 jobs:
-  deploy:
+  conditional_build_job:
     runs-on: ubuntu-latest
     steps:
-      - name: Print Successful
-        run: echo "Successful"
+    - name: Send greeting
+      run: echo "Hello"
+    - name: Failing Step
+      run: exit 1      
+    - name: Set Failure Details
+      if: failure()
+      run: echo "failure_reason=Build failed at Step 1" >> $GITHUB_ENV
+  deploy:
+    environment: dev
+    needs: conditional_build_job
+    runs-on: ubuntu-latest
+    steps:
+    - name: Send greeting
+      run: echo "Hello"
