Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,8 +30,8 @@ jobs:
     - name: Set Failure Details
       if: failure()
       run: echo "failure_reason=Build failed at Step 1" >> $GITHUB_ENV
-    - name: Sleep for 15 seconds  # Added sleep step
-      run: sleep 500s
+    # - name: Sleep for 15 seconds  # Added sleep step
+    #   run: sleep 500s
     # - name: Force failure for testing
     #   if: ${{ always() }}  # Runs even if previous steps failed
     #   run: |
@@ -46,8 +46,8 @@ jobs:
       run: echo "Hello"
     - name: Sleep for 15 seconds  # Added sleep step
       run: sleep 15s  
-    - name: Force failure for testing
-      if: ${{ always() }}  # Runs even if previous steps failed
-      run: |
-        echo "❌ Intentionally failing conditional build job"
-        exit 1  # Non-zero exit code fails the step
+    # - name: Force failure for testing
+    #   if: ${{ always() }}  # Runs even if previous steps failed
+    #   run: |
+    #     echo "❌ Intentionally failing conditional build job"
+    #     exit 1  # Non-zero exit code fails the step
